{% set name = "openff-interchange" %}
{% set version = "0.1.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-interchange/archive/0.1.0-rc.1.tar.gz
  sha256: 35022658deb4c63550e66e367da536f7ad9c8b3915f945d9a347d3614dabb8f9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - pydantic
    - openff-toolkit >=0.9.2
    - openff-units
    - openff-utilities
    - openmm
    - mdtraj
    - ele
    - panedr

test:
  imports:
    - openff.interchange

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A project (and object) for storing, manipulating, and converting molecular mechanics data.
  dev_url: https://github.com/openforcefield/openff-interchange

extra:
  recipe-maintainers:
    - mattwthompson
